context:
  version: "1.3.0"

package:
  name: communique
  version: ${{ version }}

source:
  url: https://github.com/jdx/communique/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4433f5ddde31952b8f23bf10b34faf4ed2aa89573c5c7272c7afacd416f9bbfb

build:
  number: 0
  script:
    env:
      AWS_LC_SYS_CMAKE_BUILDER: "1" # force CMake builder for `aws-lc-sys` native C code, required to make cross-compilation work
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      - if: unix
        then:
          - cargo auditable install --path=. --root="$PREFIX" --no-track --locked --bins
      - if: win
        then:
          - cargo auditable install --path=. --root="%LIBRARY_PREFIX%" --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - cmake
    - if: unix
      then: make

tests:
  - script:
      - communique --help
      - communique --version
  - package_contents:
      bin:
        - communique
      strict: true

about:
  summary: Editorialized release notes powered by AI
  description: |
    communiqué turns your Git history, pull requests, and repository context into
    polished release notes optimized for human consumption. It can print notes locally,
    update `CHANGELOG.md`, or publish directly to GitHub releases.
  license: MIT
  license_file:
    - THIRDPARTY.yml
  homepage: https://communique.jdx.dev
  repository: https://github.com/jdx/communique

extra:
  recipe-maintainers:
    - salim-b
